version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
    groups:
      radix-ui:
        patterns:
          - '@radix-ui/*'
      prisma:
        patterns:
          - 'prisma'
          - '@prisma/*'
      trpc:
        patterns:
          - '@trpc/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - ci
